#!/bin/bash

echo "🚀 Deploying the final fix for Sentry webhooks..."
echo ""
echo "SSH into your server and run these commands:"
echo ""
echo "ssh ubuntu@64.225.14.137"
echo ""
echo "# Once connected:"
echo "cd sentry_alert_tx-1/Beeper-Service"
echo "git pull origin main"
echo "docker-compose build --no-cache beeper-service  # Force rebuild without cache"
echo "docker-compose up -d beeper-service"
echo ""
echo "# Verify the fix:"
echo "docker logs -f beeper-service --tail 50"
echo ""
echo "# Also disable webhook signature if not done yet:"
echo "sed -i 's/^SENTRY_WEBHOOK_SECRET=/#SENTRY_WEBHOOK_SECRET=/' .env"
echo "docker-compose restart beeper-service"
